import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import "./globals.css";

const jamjuree = Bai_Jamjuree({
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Clipboard Landing Page Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jamjuree.className} antialiased`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
